services:
  - type: web
    name: observo-backend
    env: python
    buildCommand: pip install -r requirements_minimal.txt
    startCommand: python app/simple_backend.py
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true